### ISSUE TITLE
Controller Compiler reports XML file as unreadable

### ISSUE THREAD

**Issue by memo33** [BluelightningSC4/Network-Addon-Mod#243]
`SEVERE: The XML file "resources\xml\RUL2_IID_structure.xml" is unreadable`

This ticket serves as a reminder to check this with the next installer. If it works correctly, this ticket can be closed.

I'm not sure what causes this behavior. A possible idea is that the file in question does not exist or the program does not have the rights to access it when the installer calls the compiler, as a result of updates to the installer script.

(Besides, we should remember to update the XML file with IID patterns for code-intensive projects, such as FlexFly.)

**Comment by TarkusSC4** [comment]
In all likelihood, I'll post an internal Release Candidate for team use, for final spot checking, before we go live with the official NAM 33 build.

**Comment by TarkusSC4** [comment]
Checking before compiling the release candidate, I found two issues.  First off, there was an extraneous temporary file "RUL2_IID_structure.xml~1" that had slipped in and was causing some of the initial problems.  

Removing it caused the compiler to still fail while doing a NAM installation, though it brought up the standard warning message instead of just a note in the console window.  For some bizarre reason, the process of running the installer was corrupting "RUL2_IID_structure.xml" by duplicating line 35 (the node head for HSRP), causing it to throw a "missing </node>" error.  

From what I can tell so far, there's something in the installer script's compilation of "RUL2_IID_structure.xml" that's causing the issue.

**Comment by TarkusSC4** [comment]
Found the culprit on the new issue.  The changes to the HSRP section of the installer script to handle the new HSRP texture option was causing issues with the way the XML file was being compiled.  Reverting sec30 in the script to its original form and moving the texture option to another part of the installer solved the issue.
